/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.ResultSet;
import database.Conect;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static model.Validator.isValidPhoneNumber;
import static model.Validator.isValidIdentify;
import static model.Validator.isNumeric;




/**
 *
 * @author K.Bun29
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    CardLayout cardLayout;
    String status;
    String statusupdate;
    public Dashboard() {
        initComponents();
        buttonGroup();
        buttonGroupupdate();
        cardLayout = (CardLayout)(menu_right.getLayout());
        information.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,12));
        information.getTableHeader().setOpaque(false);
        information.getTableHeader().setBackground(new Color(32,136,203));
        information.getTableHeader().setForeground(new Color(255,255,255));
        information.setRowHeight(25);
    }
    public void buttonGroup(){
        buttonGroup1.add(paid);
        buttonGroup1.add(notpaid);
        
    }
    public void buttonGroupupdate(){
        buttonGroup2.add(paid_update);
        buttonGroup2.add(notpaid_update);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        main_panel = new javax.swing.JPanel();
        menu_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Funtions = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Show = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        menu_right = new javax.swing.JPanel();
        Add_JPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id_add = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        name_add = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        phone_add = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        address_add = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        electric_add = new javax.swing.JTextField();
        add_button = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        paid = new javax.swing.JRadioButton();
        notpaid = new javax.swing.JRadioButton();
        Update_JPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        id_update = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        name_update = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        phone_update = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        address_update = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        electric_update = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        paid_update = new javax.swing.JRadioButton();
        notpaid_update = new javax.swing.JRadioButton();
        Remove_JPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        id_remove = new javax.swing.JTextField();
        remove_button = new javax.swing.JButton();
        Pay_JPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pay_button = new javax.swing.JButton();
        id_funtionpay = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepay = new javax.swing.JTable();
        Show_JPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        information = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        search_show = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BWater Bill");
        setMaximumSize(new java.awt.Dimension(800, 665));
        setPreferredSize(new java.awt.Dimension(800, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 680));

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setForeground(new java.awt.Color(102, 102, 102));
        main_panel.setFocusable(false);
        main_panel.setMinimumSize(new java.awt.Dimension(191, 191));
        main_panel.setPreferredSize(new java.awt.Dimension(600, 800));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_panel.setBackground(new java.awt.Color(15, 18, 63));
        menu_panel.setForeground(new java.awt.Color(102, 102, 102));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");

        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/buttonleftbackground.png"))); // NOI18N
        AddButton.setText("  Add user");
        AddButton.setToolTipText("");
        AddButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddButton.setBorderPainted(false);
        AddButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddButton.setPreferredSize(new java.awt.Dimension(177, 29));
        AddButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backgroundbuttonfuntion.png"))); // NOI18N
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/buttonleftbackground.png"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UpdateButton.setBorderPainted(false);
        UpdateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UpdateButton.setPreferredSize(new java.awt.Dimension(177, 29));
        UpdateButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backgroundbuttonfuntion.png"))); // NOI18N
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        RemoveButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RemoveButton.setForeground(new java.awt.Color(255, 255, 255));
        RemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/buttonleftbackground.png"))); // NOI18N
        RemoveButton.setText("  Remove");
        RemoveButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RemoveButton.setBorderPainted(false);
        RemoveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RemoveButton.setPreferredSize(new java.awt.Dimension(177, 29));
        RemoveButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backgroundbuttonfuntion.png"))); // NOI18N
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add-user.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pay.png"))); // NOI18N
        jLabel5.setText("jLabel4");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/update.png"))); // NOI18N
        jLabel6.setText("jLabel4");

        Funtions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Funtions.setForeground(new java.awt.Color(255, 255, 255));
        Funtions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/buttonleftbackground.png"))); // NOI18N
        Funtions.setText("     Bill PayW");
        Funtions.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Funtions.setBorderPainted(false);
        Funtions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Funtions.setPreferredSize(new java.awt.Dimension(177, 29));
        Funtions.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backgroundbuttonfuntion.png"))); // NOI18N
        Funtions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuntionsActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/remove-user.png"))); // NOI18N
        jLabel7.setText("jLabel4");

        Show.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Show.setForeground(new java.awt.Color(255, 255, 255));
        Show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/buttonleftbackground.png"))); // NOI18N
        Show.setText("Show");
        Show.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Show.setBorderPainted(false);
        Show.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Show.setPreferredSize(new java.awt.Dimension(177, 29));
        Show.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/backgroundbuttonfuntion.png"))); // NOI18N
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/show.png"))); // NOI18N
        jLabel27.setText("jLabel4");

        jButton1.setBackground(new java.awt.Color(15, 18, 63));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logout.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/buttonlogount.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/admin.png"))); // NOI18N

        javax.swing.GroupLayout menu_panelLayout = new javax.swing.GroupLayout(menu_panel);
        menu_panel.setLayout(menu_panelLayout);
        menu_panelLayout.setHorizontalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menu_panelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(menu_panelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(Show, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menu_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Funtions, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RemoveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpdateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(menu_panelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton1))
                    .addGroup(menu_panelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_panelLayout.setVerticalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Funtions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(494, Short.MAX_VALUE))
        );

        AddButton.getAccessibleContext().setAccessibleParent(jSeparator2);

        main_panel.add(menu_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        menu_right.setLayout(new java.awt.CardLayout());

        Add_JPanel.setBackground(new java.awt.Color(248, 248, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel8.setText("Add customers to systems");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel10.setText("Identify of customer");

        id_add.setToolTipText("");
        id_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        id_add.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        id_add.setName(""); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setText("Name of customer");

        name_add.setToolTipText("");
        name_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        name_add.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name_add.setName(""); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel12.setText("Phone number of customer");

        phone_add.setToolTipText("");
        phone_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        phone_add.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        phone_add.setName(""); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel13.setText("Address of customer");

        address_add.setToolTipText("");
        address_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        address_add.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        address_add.setName(""); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel14.setText("Number of cubic feet of water per month");

        electric_add.setToolTipText("");
        electric_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        electric_add.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        electric_add.setName(""); // NOI18N

        add_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_button.setForeground(new java.awt.Color(255, 255, 255));
        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/iconadd.png"))); // NOI18N
        add_button.setText("Add");
        add_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add_button.setBorderPainted(false);
        add_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/iconadd1.png"))); // NOI18N
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel26.setText("Invoice status");

        paid.setText("Paid");
        paid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidActionPerformed(evt);
            }
        });

        notpaid.setText("Not paid");
        notpaid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        notpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notpaidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Add_JPanelLayout = new javax.swing.GroupLayout(Add_JPanel);
        Add_JPanel.setLayout(Add_JPanelLayout);
        Add_JPanelLayout.setHorizontalGroup(
            Add_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Add_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_add, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_add, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Add_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(id_add, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(name_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                    .addGroup(Add_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Add_JPanelLayout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paid)
                            .addGap(62, 62, 62)
                            .addComponent(notpaid))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Add_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(electric_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(752, Short.MAX_VALUE))
        );
        Add_JPanelLayout.setVerticalGroup(
            Add_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_JPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(electric_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(paid)
                    .addComponent(notpaid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(604, Short.MAX_VALUE))
        );

        id_add.getAccessibleContext().setAccessibleName("");
        id_add.getAccessibleContext().setAccessibleDescription("s");
        electric_add.getAccessibleContext().setAccessibleName("");

        menu_right.add(Add_JPanel, "Add_JPanel");
        Add_JPanel.getAccessibleContext().setAccessibleDescription("");

        Update_JPanel.setBackground(new java.awt.Color(248, 248, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel15.setText("Update customers to systems");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel16.setText("Identify of customer");

        id_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel17.setText("Name of customer");

        name_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel18.setText("Phone number of customer");

        phone_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel19.setText("Address of customer");

        address_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel20.setText("Number of cubic feet of water per month");

        electric_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        update_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update_button.setForeground(new java.awt.Color(255, 255, 255));
        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/iconadd.png"))); // NOI18N
        update_button.setText("Update");
        update_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        update_button.setBorderPainted(false);
        update_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        update_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/iconadd1.png"))); // NOI18N
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel28.setText("Invoice status");

        paid_update.setText("Paid");
        paid_update.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paid_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paid_updateActionPerformed(evt);
            }
        });

        notpaid_update.setText("Not paid");
        notpaid_update.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        notpaid_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notpaid_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Update_JPanelLayout = new javax.swing.GroupLayout(Update_JPanel);
        Update_JPanel.setLayout(Update_JPanelLayout);
        Update_JPanelLayout.setHorizontalGroup(
            Update_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Update_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_update, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_update, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_update, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_update, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addGroup(Update_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Update_JPanelLayout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paid_update)
                            .addGap(62, 62, 62)
                            .addComponent(notpaid_update))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Update_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(electric_update, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(752, Short.MAX_VALUE))
        );
        Update_JPanelLayout.setVerticalGroup(
            Update_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update_JPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Update_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Update_JPanelLayout.createSequentialGroup()
                        .addComponent(address_update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(electric_update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28))
                    .addGroup(Update_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(paid_update)
                        .addComponent(notpaid_update)))
                .addGap(18, 18, 18)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(603, Short.MAX_VALUE))
        );

        menu_right.add(Update_JPanel, "Update_JPanel");

        Remove_JPanel.setBackground(new java.awt.Color(248, 248, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel21.setText("Remove the customer from the system");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel22.setText("Identify of customer want to remove");

        id_remove.setToolTipText("");
        id_remove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        id_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        id_remove.setName(""); // NOI18N

        remove_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        remove_button.setForeground(new java.awt.Color(255, 255, 255));
        remove_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/iconadd.png"))); // NOI18N
        remove_button.setText("Remove");
        remove_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        remove_button.setBorderPainted(false);
        remove_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        remove_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/iconadd1.png"))); // NOI18N
        remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Remove_JPanelLayout = new javax.swing.GroupLayout(Remove_JPanel);
        Remove_JPanel.setLayout(Remove_JPanelLayout);
        Remove_JPanelLayout.setHorizontalGroup(
            Remove_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Remove_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Remove_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Remove_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(id_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(680, Short.MAX_VALUE))
        );
        Remove_JPanelLayout.setVerticalGroup(
            Remove_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Remove_JPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(880, Short.MAX_VALUE))
        );

        menu_right.add(Remove_JPanel, "Remove_JPanel");

        Pay_JPanel.setBackground(new java.awt.Color(248, 248, 255));
        Pay_JPanel.setPreferredSize(new java.awt.Dimension(900, 1108));

        jLabel23.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel23.setText("Pay");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel25.setText("Identify of customer want to calculate bill");

        pay_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pay_button.setForeground(new java.awt.Color(255, 255, 255));
        pay_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/iconadd.png"))); // NOI18N
        pay_button.setText("Pay");
        pay_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pay_button.setBorderPainted(false);
        pay_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pay_button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/iconadd1.png"))); // NOI18N
        pay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_buttonActionPerformed(evt);
            }
        });

        id_funtionpay.setToolTipText("");
        id_funtionpay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        id_funtionpay.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        id_funtionpay.setName(""); // NOI18N

        tablepay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone", "Address", "Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablepay);

        javax.swing.GroupLayout Pay_JPanelLayout = new javax.swing.GroupLayout(Pay_JPanel);
        Pay_JPanel.setLayout(Pay_JPanelLayout);
        Pay_JPanelLayout.setHorizontalGroup(
            Pay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pay_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(Pay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(id_funtionpay, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pay_JPanelLayout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(pay_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Pay_JPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 519, Short.MAX_VALUE))
        );
        Pay_JPanelLayout.setVerticalGroup(
            Pay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pay_JPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_funtionpay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pay_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(815, Short.MAX_VALUE))
        );

        menu_right.add(Pay_JPanel, "Funtion_JPanel");

        Show_JPanel.setBackground(new java.awt.Color(248, 248, 255));
        Show_JPanel.setPreferredSize(new java.awt.Dimension(900, 1108));

        information.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Identify", "Name", "PhoneNumber", "Address", "Water masses", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        information.setFocusable(false);
        information.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jScrollPane1.setViewportView(information);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search.png"))); // NOI18N

        search_show.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_showActionPerformed(evt);
            }
        });
        search_show.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_showKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout Show_JPanelLayout = new javax.swing.GroupLayout(Show_JPanel);
        Show_JPanel.setLayout(Show_JPanelLayout);
        Show_JPanelLayout.setHorizontalGroup(
            Show_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_JPanelLayout.createSequentialGroup()
                .addGroup(Show_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Show_JPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(search_show, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 521, Short.MAX_VALUE))
        );
        Show_JPanelLayout.setVerticalGroup(
            Show_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_JPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(Show_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_show, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(435, 435, 435))
        );

        menu_right.add(Show_JPanel, "Show_JPanel");

        main_panel.add(menu_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        cardLayout.show(menu_right, "Add_JPanel");
    }//GEN-LAST:event_AddButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        cardLayout.show(menu_right, "Update_JPanel");
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        cardLayout.show(menu_right, "Remove_JPanel");
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void FuntionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuntionsActionPerformed
        cardLayout.show(menu_right, "Funtion_JPanel");
    }//GEN-LAST:event_FuntionsActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        try {
            Connection con = Conect.getConnection();
            String identify = id_add.getText();
            String name = name_add.getText();
            String phone = phone_add.getText();
            String address = address_add.getText();
            String electric = electric_add.getText();
            if(isValidIdentify(identify) && isValidPhoneNumber(phone) && isNumeric(electric) && name != null && address != null && status != null){
                String sql = "INSERT INTO customer(identify,name,phonenumber,address,numberwater,status)" +
                    " VALUES ('"+identify+"', '"+name+"', '"+phone+"','"+address+"','"+electric+"','"+status+"')";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Add customer sucessfully");
            }
            else{
                JOptionPane.showMessageDialog(null, "Incorrect input data, try again!");
            }
            
            Conect.closeConnection(con);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error, enter again!");
        }
    }//GEN-LAST:event_add_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        try {
            Connection con = Conect.getConnection();
            if(isValidIdentify(id_update.getText()) && isValidPhoneNumber(phone_update.getText()) && isNumeric(electric_update.getText()) && name_update.getText() != null && address_add.getText() != null && status != null){
                String sql = "UPDATE customer" +
                         " SET " +
                         " identify=?" +
                         ", name=?" +
                         ", phonenumber=?" +
                         ",address=?" +
                         ", numberwater=?" +
                         ", status=?" +
                         "WHERE identify=?";
          
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1,id_update.getText());
                ps.setString(2,name_update.getText());
                ps.setString(3,phone_update.getText());
                ps.setString(4,address_update.getText());
                ps.setString(5,electric_update.getText());
                ps.setString(6,statusupdate);
                ps.setString(7,id_update.getText());
            
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Update customer sucessfully");
            }
            else{
                JOptionPane.showMessageDialog(null, "Incorrect input data, try again!");
            }
            
            Conect.closeConnection(con);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error, try again!");
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_buttonActionPerformed
        try {
            Connection con = Conect.getConnection();
            if(isValidIdentify(id_remove.getText())){
                String sql = "DELETE FROM customer WHERE identify = ?";

                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, id_remove.getText());
                ps.execute();
                JOptionPane.showMessageDialog(null, "Remove user successfully!");
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect form of identify, try again!");
            }
            
            Conect.closeConnection(con);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error, try again!");
        }
    }//GEN-LAST:event_remove_buttonActionPerformed

    private void pay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_buttonActionPerformed
        try {
            Connection con = Conect.getConnection();
            if(isValidIdentify(id_funtionpay.getText())){
                String sql = "SELECT status FROM customer WHERE identify = '"+id_funtionpay.getText()+"'";
                String sqlbill = "SELECT numberwater FROM customer WHERE identify = '"+id_funtionpay.getText()+"'";
                PreparedStatement ps = con.prepareStatement(sql);
                PreparedStatement psbill = con.prepareStatement(sqlbill);
                ResultSet rs = ps.executeQuery();
                ResultSet rsbill = psbill.executeQuery();
                
                while(rs.next() && rsbill.next()){
                String statussystem = rs.getString("status");
                String waternumber = rsbill.getString("numberwater");
                int bill = Integer.parseInt(waternumber) * 3000;
                if(statussystem.equals("Paid")){
                    JOptionPane.showMessageDialog(null, "Customer paid!");
                }else{
                    int result = JOptionPane.showConfirmDialog(null, "Cofirm action!");
                    if(result == JOptionPane.YES_OPTION){
                        String status = "Paid";
                        String sqlpay = "UPDATE customer" +
                         " SET " +
                         " status='"+status+"'" +
                         "WHERE identify='"+id_funtionpay.getText()+"'";
                        PreparedStatement ps1 = con.prepareStatement(sqlpay);
                        ps1.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Customer paid: " + bill);
                    }else if(result == JOptionPane.NO_OPTION){
                        break;
                    }else if(result == JOptionPane.CANCEL_OPTION){
                        break;
                    }   
                } 
            }
            }else{
                    JOptionPane.showMessageDialog(null, "Incorrect form of identify, try again!");
            }
            
            Conect.closeConnection(con);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error, try again!");
        }
    }//GEN-LAST:event_pay_buttonActionPerformed

    private void paidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidActionPerformed
        status = paid.getText();
    }//GEN-LAST:event_paidActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        cardLayout.show(menu_right, "Show_JPanel");
        try {
            Connection con = Conect.getConnection();
            String sql = "SELECT * FROM customer";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel)information.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
            } 
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error system, try later!");
        }
    }//GEN-LAST:event_ShowActionPerformed

    private void notpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notpaidActionPerformed
        status = notpaid.getText();
    }//GEN-LAST:event_notpaidActionPerformed

    private void paid_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paid_updateActionPerformed
        statusupdate = paid_update.getText();
    }//GEN-LAST:event_paid_updateActionPerformed

    private void notpaid_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notpaid_updateActionPerformed
        statusupdate = notpaid_update.getText();
    }//GEN-LAST:event_notpaid_updateActionPerformed

    private void search_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_showActionPerformed

    private void search_showKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_showKeyReleased
        DefaultTableModel find = (DefaultTableModel)information.getModel();
        TableRowSorter<DefaultTableModel> find1 = new TableRowSorter<>(find);
        information.setRowSorter(find1);
        find1.setRowFilter(RowFilter.regexFilter(search_show.getText()));
    }//GEN-LAST:event_search_showKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int result = JOptionPane.showConfirmDialog(null, "Cofirm action!");
                    if(result == JOptionPane.YES_OPTION){
                        this.dispose();
                        Login login = new Login();
                        login.setVisible(true);
                    }else if(result == JOptionPane.NO_OPTION){
                        
                    }else if(result == JOptionPane.CANCEL_OPTION){
                       
                    }   
    }//GEN-LAST:event_jButton1ActionPerformed
       
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JPanel Add_JPanel;
    private javax.swing.JButton Funtions;
    private javax.swing.JPanel Pay_JPanel;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JPanel Remove_JPanel;
    private javax.swing.JButton Show;
    private javax.swing.JPanel Show_JPanel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel Update_JPanel;
    private javax.swing.JButton add_button;
    private javax.swing.JTextField address_add;
    private javax.swing.JTextField address_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField electric_add;
    private javax.swing.JTextField electric_update;
    private javax.swing.JTextField id_add;
    private javax.swing.JTextField id_funtionpay;
    private javax.swing.JTextField id_remove;
    private javax.swing.JTextField id_update;
    private javax.swing.JTable information;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JPanel menu_right;
    private javax.swing.JTextField name_add;
    private javax.swing.JTextField name_update;
    private javax.swing.JRadioButton notpaid;
    private javax.swing.JRadioButton notpaid_update;
    private javax.swing.JRadioButton paid;
    private javax.swing.JRadioButton paid_update;
    private javax.swing.JButton pay_button;
    private javax.swing.JTextField phone_add;
    private javax.swing.JTextField phone_update;
    private javax.swing.JButton remove_button;
    private javax.swing.JTextField search_show;
    private javax.swing.JTable tablepay;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
